class StandardEvents {
  StandardEvents._();
  static String GAMEOLIVE_GAME_ROUND_STARTED = "GAMEOLIVE_GAME_ROUND_STARTED";
  static String GAMEOLIVE_GAME_ROUND_ENDED = "GAMEOLIVE_GAME_ROUND_ENDED";
  static String GAMEOLIVE_GAME_GOTO_HOME = "GAMEOLIVE_GAME_GOTO_HOME";
  static String GAMEOLIVE_BALANCE_CHANGE = "GAMEOLIVE_GAME_BALANCE_CHANGE";
  static String GAMEOLIVE_USER_ACHIEVEMENTS_UPDATE =
      "GAMEOLIVE_USER_ACHIEVEMENTS_UPDATE";
}
